### ISSUE TITLE
TASK [gbraad.kubernetes-master : Configure etcd ADVERTISE CLIENTS]  fail

### ISSUE THREAD

**Issue by dimthe** [gbraad/ansible-playbook-kubernetes#2]
hello 
i am trying to execute your role and it fails at the below step. can you give some tips? thanks
this is on atomic centos

TASK [gbraad.kubernetes-master : Configure etcd ADVERTISE CLIENTS] *******************************************************************************************************************************************
ERROR! The requested handler 'restart etcd' was not found in either the main handlers list nor in the listening handlers list

**Comment by gbraad** [comment]
You likely have to rename the handler, however I believe this was already fixed some time ago. Else, this broke due to a newer/older version of Ansible.
